config/routes.rb
Rails.application.routes.draw do

	get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
    get '/signup' => 'users#new'
    get '/auth/facebook/callback' => 'sessions#create'

	resources :users
	resources :games do
		resources :matches
	end

	resources :scythes, only: [:index]


	root :to => 'welcome#index'
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
	has_many :matches
	has_many :users, through: :matches
	validates :name, uniqueness: true
	# scope :favorite, -> {where(
	# }

def self.favorite
	games = self.all.collect do |game|
	 		game.matches.count
	 		game.name
	 	end

	games.group_by{|x| x}.sort_by{|k, v| -v.size}.map{|game| game.first}.first
end




end

app/models/match.rb
class Match < ApplicationRecord
	belongs_to :game
	belongs_to :user
	has_one :scythe, inverse_of: :match, :dependent => :destroy
	accepts_nested_attributes_for :scythe

	
end

app/models/scythe.rb
class Scythe < ApplicationRecord
	belongs_to :match, inverse_of: :scythe
	validates_presence_of :match

	scope :faction, -> { group("faction") }



	def self.count_played_faction
		count.sort_by {|k, v| v}.reverse[0][0]
	end

end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password
	has_many :matches
	has_many :games, through: :matches
	validates :email, uniqueness: true, case_sensitive: false
	validates_format_of   :email, with: /@/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user, :logged_in?, :require_login

 	def current_user
 		@current_user ||= User.find_by(id: session[:user_id])
 	end

 	def logged_in?
 		!!current_user
 	end

 	def require_login
		if !logged_in?
			flash[:notice] = "You must be logged in to add a game."
			redirect_to root_path
		end
	end	

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :require_login

	def new
		@game = Game.new
		@games = Game.all
	end

	def create
			@game = Game.find_or_initialize_by(game_params)
			
			if Game.where(:id => @game.id).exists?
				redirect_to new_game_match_path(@game)
			elsif @game.save
			redirect_to new_game_match_path(@game)
			else
				flash[:notice] = "That game could not be added. Please try again."
				redirect_to new_game_path
			end
	end

	def show
		@game = Game.find(params[:id])
		render json: @game, status: 200
	end

	

	private

	def game_params
		params.require(:game).permit(:name)
	end

	
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
	before_action :require_login

	def index
		@matches = Match.all

	end

	def new
		set_game
		@games = Game.all
		@match = Match.new

		# render :new, layout: false
	end

	def create
		set_game
	    @match = @game.matches.build(match_params)
	    @match.user = current_user

	    if @match.save
	    	flash[:notice] = "Your match was successfully added!"
	      redirect_to game_match_path(@game, @match)

	     # "games/#{@game.id}/matches/#{@match.id}"
	      # games/:game_id/matches/:id

	    else
	      redirect_to root_path
	    end
	end

	def show
		set_game
		set_match
		@user = current_user

	end

	def edit
		set_game
		set_match
	end

	def update
		set_game
		set_match

		if @match.update(match_params)
		flash[:alert] = "Your match was successfully updated."
		redirect_to game_match_path(@game, @match)
		else
	      redirect_to root_path
	    end
	end

	def destroy
		set_game
		set_match
		@user = current_user
		@match.destroy
		flash[:alert] = "Your match was successfully deleted."
		redirect_to user_path(@user.id)
	end

	private

	def match_params
		params.require(:match).permit(:user_id, :game_id, :match_date, :win, scythe_attributes: [:faction, :player_mat, :score, :winning_score, :turns, :players, :airships, :winner])
	end

	def set_game
		@game = Game.find(params[:game_id])
	end

	def set_match
		@match = Match.find(params[:id])
	end

	
end

app/controllers/scythes_controller.rb
class ScythesController < ApplicationController
	before_action :require_login
	

	def index
		@favorite = Scythe.faction.count_played_faction
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@user = User.new
  end

  def create
    if auth
    	 @user = User.find_or_create_by(uid: auth['uid']) do |u|
        u.name = auth['info']['name']
        u.email = auth['info']['email']
        u.image = auth['info']['image']
        u.password = SecureRandom.hex
        end
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      

  	else
      @user = User.find_by(email: params[:user][:email])

      if @user && @user.authenticate(params[:user][:password])
  		session[:user_id] = @user.id
  		redirect_to user_path(@user)
  	  else
      flash[:alert] = "Invalid email/password combination"
      redirect_to root_path
  	  end
    end
  end

  def destroy
  	reset_session
  	redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
require 'pry'
class UsersController < ApplicationController
	before_action :require_login, only: [:show]
	before_action :set_user, only: [:show]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
	
		if @user.save
			session[:user_id] = @user.id
			redirect_to user_path(@user.id)
		else
			flash[:notice] = "Incorrect Signup Form Entrie(s), please try again"
			redirect_to signup_path
		end
	end

	def show
		if logged_in?
			set_user
			@games = @user.games.all.uniq
			@fav = @user.games.favorite 
			respond_to do |format|
      			format.html { render :show }      # Render post in HTML format
      			format.json { render json: @user } # Render post in JSON format
   			end
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :uid, :image)
	end

	def set_user
		@user = User.find(params[:id])	
	end

	def require_login
		if !logged_in?
			redirect_to root_path
		end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/match_helper.rb
module MatchHelper
	def total_matches(game)
		game.matches.count
	end
end

app/helpers/scythes_helper.rb
module ScythesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
	def current_user_page(current_user)
		if request.path.include?("#{current_user.id}")
			link_to('Add a match here', new_game_path, id: 'get-new-game-form')
		end
	end

	def win_column(match)
		 if match.win == true 
              "Yes" 
             else 
              "No" 
             end 
	end
end

app/views/games/_form.html.erb
<%= form_for [@game] do |f| %>


	
	<%= f.label 'Game Name:' %><br>
	<%= f.text_field :name %><br><br>

	<%= f.submit 'Next' %>

<% end %>

app/views/games/new.html.erb
<%= render 'form'%>

app/views/games/show.html.erb
<%= @game.name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
    <meta name="description" content="Tabletop Tracker">
    <title>Tabletop Tracker</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="<%= root_path %>"/>Home</a>
        <% if !logged_in? %>
        <a class="navbar-brand" href="/signup"/>Sign Up</a>
        <a class="navbar-brand" href="/login">Log in</a>
        <% end %>
        <% if logged_in? %>
        <a class="navbar-brand" href="<%= user_path(current_user) %>">My Stats</a>
        <a class="navbar-brand" href="/logout">Log Out</a>
        <% end %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class="alert"><%= flash[:alert] %></div>
      <% end %>

      <%= yield %>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  </body>
</html>

app/views/matches/_form.html.erb
<%= form_for [@game, @match] do |f| %>

		<%= f.label :match_date %>
		<%= f.date_field :match_date %><br>

		<%= f.label 'Did you win?' %>
		<%= f.check_box :win %><br>
		

	<% if @game.name == "Scythe" %>

		

		<%= f.fields_for :scythe_attributes do |scythe| %>

	           <%= scythe.label :faction %>
			    <%= scythe.text_field :faction %><br>

				<%= scythe.label :player_mat %>
			    <%= scythe.text_field :player_mat %><br>

			    <%= scythe.label :score %>
			    <%= scythe.number_field :score %><br>

			    <%= scythe.label :winning_score %>
			    <%= scythe.number_field :winning_score %><br>

			    <%= scythe.label :turns %>
			    <%= scythe.number_field :turns %><br>

			    <%= scythe.label :players %>
			    <%= scythe.number_field :players %><br>
			
				<%= scythe.label :airships %>
				<%= scythe.check_box :airships %><br>

				<%= scythe.label 'Who won, if not you?' %>
				<%= scythe.text_field :winner %><br>

	       <% end %>
	   	
 
	   	


	
	<% end %>

	<%= f.submit %>
	 
<% end %>

app/views/matches/_show.html.erb
<% if @game.name == "Scythe" %>

<p>Faction: <%=  @match.scythe.faction %></p>
<p>Player Mat: <%=  @match.scythe.player_mat %></p>
<p>Score: <%=  @match.scythe.score %></p>
<p>Winning Score: <%=  @match.scythe.winning_score %></p>
<p>Total Turns: <%=  @match.scythe.turns %></p>
<p>Total Players: <%=  @match.scythe.players %></p>
<% if @match.scythe.airships %>
<p>This match included Wind Gambit.</p>
<% end %>
<% if !@match.win %>
<p>Winner: <%=  @match.scythe.winner %></p>
<% end %>

<% end %>

<% if @match.win == true %>

<h4>You won on <%= @match.match_date %>.</h4><br>

<% else %>

<h4>You played on <%= @match.match_date %></h4><br>
<h2>Better luck next time!</h2><br>



<% end %>

app/views/matches/edit.html.erb
<h1>Edit match</h1>

<%= form_for [@game, @match] do |f| %>

		<%= f.label :match_date %>
		<%= f.date_field :match_date %><br>

		<%= f.label 'Did you win?' %>
		<%= f.check_box :win %><br>
		

	<% if @game.name == "Scythe" %>

		

		<%= f.fields_for :scythe_attributes do |scythe| %>

	           <%= scythe.label :faction %>
			    <%= scythe.text_field :faction, value: "#{@match.scythe.faction}" %><br>

				<%= scythe.label :player_mat %>
			    <%= scythe.text_field :player_mat %><br>

			    <%= scythe.label :score %>
			    <%= scythe.number_field :score %><br>

			    <%= scythe.label :winning_score %>
			    <%= scythe.number_field :winning_score %><br>

			    <%= scythe.label :turns %>
			    <%= scythe.number_field :turns %><br>

			    <%= scythe.label :players %>
			    <%= scythe.number_field :players %><br>
			
				<%= scythe.label :airships %>
				<%= scythe.check_box :airships %><br>

				<%= scythe.label 'Who won, if not you?' %>
				<%= scythe.text_field :winner %><br>

	       <% end %>
	   	
 
	   	


	
	<% end %>

	<%= f.submit %>
	 
<% end %>

app/views/matches/index.html.erb
<% @matches.each do |match| %>
<%= match.match_date %><br>

<% end %>

app/views/matches/new.html.erb
<h1>Add a match</h1>

<%= render 'form'%>

app/views/matches/show.html.erb
<%= render 'show'%>


<!-- <h5>You have played <%= @game.name %> <%= total_matches(@game) %> times! </h5><br> -->
<%= link_to 'Edit Match', edit_game_match_path(@game, @match) %><br>
<%= link_to 'Delete Match', game_match_path(@game, @match), method: :delete, confirm: "Are you sure?" %><br>

<%= link_to 'Back to All of Your Matches', user_path(@user.id) %>

app/views/scythes/index.html.erb
<%= @favorite %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %><br>

	<%= f.label :email %>
	<%= f.text_field :email %><br>

	<%= f.label 'password' %>
	<%= f.password_field :password %><br>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %><br>

	<%= f.submit %>

<% end %>

app/views/users/new.html.erb
<h1>Create an Account </h1>

<%= render 'form'%>

app/views/users/show.html.erb
<a href="#" class="userName" data-id="<%= @user.id %>"><h1 id="username" ><%= @user.name %>'s Stats </h1></a>


<ul id="user-games"></ul>

























<% if current_user_page(current_user) %>
  <% if current_user.matches.count >= 1  %>
    <p>Your favorite game is <%= @fav %>. 
  <% end %>
<% end %>

<h3><%= current_user_page(current_user) %></h3>

<div id="new-game-form">************ PLACEHOLDER *************</div>

app/views/welcome/index.html.erb
<h1>Welcome to Tabletop Tracker!</h1>
<h4>A place for you to keep track of your tabletop gaming history. </h4>
<% if logged_in? %>
    <h3><a href="<%= user_path(current_user) %>">Go to My Stats</a></h3>
<% else %>
<h2>New to TT? Sign up <%= link_to 'here', signup_path %>.</h2>
<h2>Already have an account? Log in <%= link_to 'here', login_path %>.</h2>
<%= link_to('Log in with Facebook!', '/auth/facebook') %>
<% end %>